### ISSUE TITLE
Can I use this in my application?

### ISSUE THREAD

**Issue by sks316** [Mcdonoughd/jetsetradiofuture.live#1]
Hi, I'm the developer of [sks316/JSRLoader](https://github.com/sks316/JSRLoader/), a music downloader for JetSetRadioLive. I stumbled across this clone of JSRL yesterday, and I have to say, I'm quite impressed that you've managed to clone the entirety of JSRL from the Wayback Machine.
I decided to update my application yesterday, and found some content was removed server-side. I figured I'd have to remove these stations from the downloader in the next release, then I found your clone. I figure I could just patch the URLs for these stations to load from jetsetradiofuture.live instead of from jetsetradio.live, but I thought I should ask first, are you okay with me doing that?
Thanks!

**Comment by Mcdonoughd** [comment]
Hello, thank you for reminding me I should update the site to add the new stations. Many tracks and stations were either moved around or removed. You're welcome to use the site as long as its up.

**Comment by sks316** [comment]
Awesome, thank you!
