### ISSUE TITLE
Where is the music comming from?

### ISSUE THREAD

**Issue by chaz4short** [Mcdonoughd/jetsetradiofuture.live#14]
First off, This is such a kool project. Loved the game (Future), I want to try a version of this but while I think I can understand most of the functions I cant seem to understand where the music is coming from.

Is there a service you are interacting with? if so can you point where that is happening?

**Comment by sks316** [comment]
The website is an archive of [JetSetRadio.live](https://jetsetradio.live), it serves the music by itself.

[Here's an example.](https://jetsetradiofuture.live/radio/stations/classic/B.B.%20Rights%20-%20Funky%20Radio.mp3)

**Comment by chaz4short** [comment]
Sweet So i would assume, the Music files are there in the Repo? or at least should be if the files/songs are going to play right?

**Comment by Mcdonoughd** [comment]
Music files are not on the repository because some files are either too big, or potentially break github [TOS](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies#9-excessive-bandwidth-use )
You can find collections of the material [elsewhere](https://archive.org/details/jsrl_collection).

**Comment by BenSFGamer** [comment]
Learn something new every day.

**Comment by BenSFGamer** [comment]
I wasn't aware that there was an archive. Seen a couple of jsrl here and
the on wayback but not this.

Side note, I known you've been busy or taking a break but I've pushed a
station to the refractor. You should be able to see it.

Also, I can't do anything with putty ssh. No luck on my end. Need another
method of running the jsrl on my end.
